col = [".MOPA"
"SIOUX"
"ZTREJ"
"VBXRO"
"DEIO."
".QMRH"
"VBXRO"
"VTNEN"
"HBCIW"
"IYBWU"
"QLR.."
"XBTUP"
"HOEIT"
"MDJQP"
"CGEUZ"
"WY.GE"
"RNBFH"
"EHGYD"
"K.OG."
"CBRUZ"
"EVBEO"
"BEJF."
"BFKAR"
"LONOE"
"ERNLH"
".CFJ."
"ICRAM"
".USSA"
"SEDUE"
"RET.."
"VFILT"
"XGLDY"
"PUALK"
"L.H.."
"OR.OS"
"OMIVE"
".SWAJ"
"F.D.V"
"PPOLP"
"VOLSA"
"DTTOR"
"SPBTS"
"GPMRQ"
"VJPMA"
"..LSH"
"GOOKL"
"POMDS"
"AUGLO"
"LG..Z"
"VXQBY"]

# char ~ int  : ~('b') ~(2)
~a=a-'A'+1
~n::Int=n+'A'-1

function printm(a)
    for j in 1:5
    for i in a
        print(col[i][j])
    end
    println()
    end
end
a = [10,13,48,31,25,24,36,8,18,5]
printm(a)

pairs = [
 1 20 33 52 0 12 18 5 39 1 12 57 26 181 1 20 1 75 95 104 9 20 13 1 26 1;
 11 1 0 0 47 0 0 0 6 1 0 17 0 0 19 0 0 11 2 1 21 0 0 0 11 0;
 31 0 4 0 38 0 0 38 10 0 18 9 0 0 45 0 1 11 1 15 7 0 0 0 1 0;
 48 20 9 13 57 11 7 25 50 3 1 11 14 16 41 6 0 14 35 56 10 2 19 0 10 0;
 110 23 45 126 48 30 15 33 41 3 5 55 47 111 33 28 2 169 115 83 6 24 50 9 26 0;
 25 2 3 2 20 11 1 8 23 1 0 8 5 1 40 2 0 16 5 37 8 0 3 0 2 0;
 24 3 2 2 28 3 4 35 18 1 0 7 3 4 23 1 0 12 9 16 7 0 5 0 1 0;
 114 2 2 1 302 2 1 6 97 0 0 2 3 1 49 1 0 8 5 32 8 0 4 0 4 0;
 10 5 32 33 23 17 25 6 1 1 8 37 37 179 24 6 0 27 86 93 1 14 7 2 0 2;
 2 0 0 0 2 0 0 0 3 0 0 0 0 0 3 0 0 0 0 0 8 0 0 0 0 0;
 6 1 1 1 29 1 0 2 14 0 0 2 1 9 4 0 0 0 5 4 1 0 2 0 2 0;
 40 3 2 36 64 10 1 4 47 0 3 56 4 2 41 3 0 2 11 15 8 3 5 0 31 0;
 44 7 1 1 68 2 1 3 25 0 0 1 5 2 29 11 0 3 10 9 8 0 4 0 18 0;
 40 7 25 146 66 8 92 16 33 2 8 9 7 8 60 4 1 3 33 106 6 2 12 0 11 0;
 16 12 13 18 5 80 7 11 12 1 13 26 48 106 36 15 0 84 28 57 115 12 46 0 5 1;
 23 1 0 0 30 1 0 3 12 0 0 15 1 0 21 10 0 18 5 11 6 0 1 0 1 0;
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 0 0 0 0 0;
 50 7 10 20 133 8 10 12 50 1 8 10 14 16 55 6 0 14 37 42 12 4 11 0 21 0;
 67 11 17 7 74 11 4 50 49 2 6 13 12 10 57 20 2 4 43 109 20 2 24 0 4 0;
 59 10 11 7 75 9 3 330 76 1 2 17 11 7 115 4 0 28 34 56 17 1 31 0 16 0;
 7 5 12 7 7 2 14 2 8 0 1 34 8 36 1 16 0 44 35 48 0 0 2 0 1 0;
 5 0 0 0 65 0 0 0 11 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 1 0;
 66 1 1 2 39 1 0 44 39 0 0 2 1 12 29 0 0 3 4 4 1 0 2 0 1 0;
 1 0 2 0 1 0 0 0 2 0 0 0 0 0 0 3 0 0 0 3 0 0 0 0 0 0;
 18 7 6 6 14 7 3 10 11 1 1 4 6 3 36 4 0 3 19 20 1 1 12 0 2 0;
 1 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
]

imp = zeros(Int,50,50)


for i in 1:50
    for j in 1:50
        imposibauauaule = false
        for k in 1:5
            a = col[i][k]
            b = col[j][k]
            if a!='.'&&b!='.'
                proba = pairs[~b,~a]
                if proba == 0
                    imposibauauaule = true
                else
                    imp[i,j]+=proba
                end
            else
                imp[i,j]+=50
            end
        end
        if imposibauauaule
            imp[i,j] = 0
        end
    end
end

next = [sortperm(imp[i,:], rev = true) for i in 1:50]

function findnext(a,i)
    j = 1
    while next[i][j] in a
        j+=1
    end
    return next[i][j]
end

for i in 1:50
    a = Int[]
    push!(a,i)
    while length(a)<50
        i = a[end]
        j = findnext(a,i) # findmax(imp[i,:])[2]
        push!(a,j)
    end
    printm(a)
    println()
end

function searchword(w)
    for line in 1:5
        searchword(w,line)
    end
end
function searchword(w,line)
    sols = [findall(x->x[line]==c,col) for c in w]
    println(sols)
    # pool = []
    # getpool(pool,sols,1)
    # sols2 = [[o] for i in sols[o] for o in 1:length(sols)]#, j in sols[2], k in sols[3], l in sols[4], m in sols[5]]
    sols2 = [[i,j,k,l,m] for i in sols[1], j in sols[2], k in sols[3], l in sols[4], m in sols[5]]
    # sols2 = [[i,j,k] for i in sols[1], j in sols[2], k in sols[3]]
    for n in sols2
        printm(n)
        println()
    end
    for i in 1:length(sols)-1
        s1 = sols[i]
        s2 = sols[i+1]
        for a in s1
            for b in s2

                # println(a,' ',b,' ',imp[a,b])
            end
        end
    end
end

w = "REVOLUTION"
w = "WHICH"
line = 4
searchword(w)

most_used = ["THE","OF","AND","TO","IN","A","IS","WAS","THAT","FOR","AS","WITH","BY","ON","ARE","FROM","BE","OR","HIS","WERE","IT","AN","AT","NOT","WHICH","HAVE","HE","HAD","THIS","HAS","ALSO","THEIR","BUT","ONE","CAN","ITS","ONTHE","OTHER","BEEN","MORE","THEY","USED","FIRST","ALL","TWO","CITATION","THAN","INTO","WOULD","ONLY","TIME","WHO","MOST","MAY","SUCH","SOME","MANY","WHEN","AFTER","BETWEEN","OVER","THESE","HER","ABOUT","THERE","USE","NO","THEM","NEW","HIM","WILL","OUT","DURING","MADE","BOTH","THEN","OFTEN","SO","ANY","BEING","SUCHAS","WHERE","NUMBER","COULD","MAIN","P.","THROUGH","SYSTEM","PEOPLE","KNOWN","EACH","WHILE","IF","CALLED","CONVERT","SAME","LATER","THREE","BECAUSE","WELL","WORK","BEFORE","THESAME","UNDER","PART","VERY","DIFFERENT","BECAME","YEAR","DID","LARGE","EXAMPLE","SEVERAL","CITY","EARLY","UNTIL","MUCH","GOVERNMENT","FOUND","OWN","SINCE","SHE","EVEN","FORM","POWER","DO","THOSE","AROUND","STATE","INCLUDING","SET","HIGH","LIFE","AGAINST","SECOND","CENTURY","WITHIN","WORLD","STILL","END","USING","SMALL","NAME","WHAT","NOW","USUALLY","AMERICAN","WITHOUT","HOWEVER","BEGAN","LIKE","ASWELL","AREA","MAKE","COMMON","THEMOST","WATER","UNITEDSTATES","ANOTHER","WAY","DUE","MUST","LONG","LESS","FOUR","DEATH","SAID","FILM","ORDER","DUETO","BACK","PUBLIC","DOES","LEFT","BASED","FEW","BECOME","KNOWNAS","S","GIVEN","COUNTRY","MAJOR","BRITISH","PLACE","GROUP","CONSIDERED","AMONG","GAME","POINT","USEDTO","PERIOD","SUPPORT","WAR","MUSIC","DOWN","MILLION","IMPORTANT","SYSTEMS","CONTROL","SHOULD","TOOK","DAY","FAMILY","LANGUAGE","LAST","ORIGINAL","RESULT","POLITICAL","LINE","MEMBERS","CASE","ASWELLAS","SEE","SINGLE","JUST","PROCESS","ALONG","SIMILAR","TAKE","FOLLOWING","WE","ALTHOUGH","COUNTRIES","RIGHT","EITHER","TIMES","AREAS","PUBLISHED","THEOTHER","LOCAL","INCLUDE","POPULATION","NEVER","DATA","HOME","EVERY","VARIOUS","THETIME","MODERN","FURTHER","DEVELOPMENT","PER","HOW","LED","POSSIBLE","MILITARY","POPULAR","TERM","THOUGH","HISTORY","GENERALLY","YOU","OFF","RATHER","MEN","LAW","DEVELOPED","GERMAN","HELD","HUMAN","PRODUCTION","BODY","GENERAL","THEWORLD","LIGHT","SOMETIMES","STATES","LATE","FIELD","BASEDON","HAVING","CAME","ABOVE","AVAILABLE","BOOK","OTHERS","YORK","NEXT","CREATED","U.S.","SHOW","HIMSELF","OUTOF","WROTE","DAYS","DIED","WORD","PLAY","AGAIN","GREAT","SERVICE","AGE","SEEN","CHILDREN","LEVEL","RELEASED","WORKS","CONTINUED","PP.","THETWO","FIVE","HIGHER","SPECIES","ENERGY","REQUIRED","CHANGE","MEANS","TEAM","JANUARY","INFORMATION","THEORY","NEWYORK","PRODUCED","MAKING","BUILT","DESIGN","ROLE","ADDITION","INCLUDED","ALMOST","SIDE","POSITION","GROUPS","ABLE","DE","LAND","TOTAL","RANGE","JULY","NATIONAL","SPACE","WRITTEN","SOCIAL","VERSION","EUROPE","SEASON","FORCE","AIR","ALLOWED","LARGEST","GOOD","TYPE","ITSELF","RECEIVED","WOMEN","LOW","THROUGHOUT","TAKEN","STANDARD","LITTLE","LEAST","THATIS","FREE","CASES","SIZE","THUS","SCHOOL","ESPECIALLY","OLD","UPON","PARTICULAR","TERMS","EFFECT","PROVIDE","LOWER","CERTAIN","TOGETHER","PRESENT","ALWAYS","SHORT","PARTS","WORDS","THIRD","APRIL","DESCRIBED","TOO","UPTO","ESTABLISHED","MIGHT","PLAYED","FORCES","NATURAL","JUNE","ONCE","MONTHS","RATE","EUROPEAN","NUMBERS","SIX","MAN","RATHERTHAN","HAND","TYPICALLY","VALUE","ENGLAND","LONDON","OCTOBER","COULDBE","FINAL","THECOUNTRY","SEPTEMBER","AVERAGE","FRANCE","INSTEAD","CURRENT","DECEMBER","INTERNATIONAL","PROGRAM","CHARACTER","INCREASED","AFEW","SURFACE","ACROSS","THOUGHT","COMPANY","FOLLOWED","BEST","PROVIDED","ECONOMIC","GAMES","SIGNIFICANT","NAMED","FUNCTION","BUILDING","WENT","RETURN","USES","FACT","STUDY","BELOW","FULL","SOURCE","LOST","AMERICA","PERSON","ANUMBER","CHANGES","LONGER","RESEARCH","INDIVIDUAL","LANGUAGES","STRONG","STRUCTURE","PARTY","LARGER","RUN","OPEN","CAUSE","AIRCRAFT","AWAY","FAR","REGION","NEED","FOOD","FORMS","INCREASE","OUTSIDE","STARTED","MATERIAL","CANNOT","NOVEMBER","HALF","HEAD","MARKET","NEAR","RECORD","TRADITIONAL","SPECIAL","STYLE","ALLTHE","SENT","STORY","FEBRUARY","PLAYER","DESIGNED","TOP","ATLEAST","THEMSELVES","MODEL","RETURNED","BAND","BECAUSEOF","HELP","TYPES","COME","POINTS","ADDED","EVENTS","NETWORK","LIMITED","SERVICES","NATURE","ARMY","FORMER","FATHER","CLOSE","VIEW","ALLOW","WON","SPECIFIC","ELEMENTS","PRACTICE","LINES","GAVE","PRESSURE","INTRODUCED","PRODUCE","MOVED","WHETHER","RELIGIOUS","PUT","OFFICIAL","MOVEMENT","MY","GERMANY","STUDENTS","TRADE","METHOD","ATTACK","INORDER","PROBLEMS","ART","EVENTUALLY","EVIDENCE","REFERRED","RESULTS","CAUSED","REMAINED","INFLUENCE","SUCCESS","MEANING","BROUGHT","BELIEVED","ENOUGH","FEATURES","GIVE","YOUNG","WHITE","CULTURE","PROBLEM","CHARACTERS","LEAD","ACTION","ACCORDING","REFERREDTO","CONDITIONS","PERFORMANCE","ACCORDINGTO","EFFECTS","AMOUNT","BLACK","BUSINESS","WORKING","BETTER","DIFFICULT","TEMPERATURE","EDUCATION","REAL","MONEY","SMALLER","CREATE","LOCATED","DIRECTLY","SOUND","LEADING","GROUND","THEREFORE","GET","PRIVATE","FORMED","PARTICULARLY","CHINESE","TELEVISION","SUBJECT","SOUTH","CITIES","ALBUM","CLASS","INDUSTRY","COMPUTER","BEGINNING","COMMUNITY","ALREADY","COMPLETE","GO","PLAYERS","ASSOCIATED","RELATED","PHYSICAL","OUR","TOWN","MOVE","COMPLEX","INTEREST","RULE","SPEED","COMMONLY","INORDERTO","RIGHTS","LIVING","FOREXAMPLE","GREATER","WRITING","FIND","GROWTH","KILLED","COURT","LEVELS","HOUSE","AGAINSTTHE","OFFICE","DONE","SHOWS","SPANISH","NEEDED","SAW","CENTRAL","ENTIRE","FIRE","SON","BOOKS","MOSTLY","ACCESS","SOON","TODAY","EARLIER","VARIETY","ADDITIONAL","PERCENT","FOREIGN","EVER","RECORDED","FUTURE","WIDELY","TITLE","ALLOF","SHOWN","SUCCESSFUL","RADIO","PROJECT","CONSTRUCTION","CHANGED","KING","REMAINS","MASS","PERSONAL","POLICY","CODE","INCLUDES","INVOLVED","AFRICA","IDEA","NAMES","SEPARATE","BASE","LENGTH","RULES","KEY","UNITS","LIKELY","MAKES","RELEASE","COST","CHURCH","FILMS","MAJORITY","PRIMARY","PERFORMED","METHODS","STATED","APPEAR","WHOLE","SOTHAT","MEMBER","ALLOWS","DECIDED","JAPANESE","REPORTED","SOLD","CAPITAL","SCIENCE","SOCIETY","REST","STAGE","EVENT","WHOSE","RECENT","COLOR","LEGAL","HIGHLY","CAREER","SONG","FREQUENTLY","PLACED","SIMPLE","DEFINED","ME","MOTHER","APPEARED","INDIA","SCHOOLS","TURN","SIMPLY","RELATIONSHIP","MULTIPLE","NEARLY","SENSE","PAST","RELATIVELY","FORCED","SOFTWARE","ATTEMPT","NORTH","WILLIAM","QUICKLY","COMPANIES","PROGRAMS","PRODUCTS","DIRECT","SITE","SOURCES","PREVIOUS","TECHNOLOGY","BATTLE","FRONT","PROVIDES","NECESSARY","SERVED","ORIGINALLY","ALONGWITH","APPROACH","IMAGE","SEVEN","EXPERIENCE","GREEK","PARTSOF","TEXT","TOWARDS","COMPLETED","MEMORY","ABILITY","COMMERCIAL","UK","HEALTH","REPLACED","WORKED","YET","START","ECONOMY","HIGHEST","PROPERTY","BEHIND","KNOWLEDGE","TEST","RESPONSE","LARGELY","SEA","REACHED","PRESIDENT","WIDE","NIGHT","OPERATIONS","SUPPORTED","ACT","TRAINING","REASON","BRITAIN","LIST","ISSUES","OCCUR","LOSS","THEGOVERNMENT","REDUCED","ACTIVE","FUNCTIONS","REMAIN","LACK","TODO","CLEAR","GAS","ISLAND","CELLS","TAKING","CONTAINS","TAKES","APPROXIMATELY","EXIST","BASIS","DISTANCE","INDEPENDENT","INTENDED","ELECTED","PRODUCT","ADOPTED","ACTUALLY","WIFE","ENDED","BORN","CHRISTIAN","KEEP","POTENTIAL","COURSE","MATTER","LOVE","ISSUE","OBJECTS","THINGS","HEAVY","OIL","CENTER","REGULAR","GEORGE","THEFOLLOWING","DIVIDED","EIGHT","DATE","JAMES","SUMMER","DIRECTION","LAWS","NUMEROUS","ACCOUNT","INCOME","INDIVIDUALS","CONCEPT","PLAN","ANNOUNCED","RUSSIAN","FAILED","APPLIED","VALUES","NORTHERN","PROPOSED","SHIPS","RESULTING","ESTIMATED","APPEARS","CONTINUE","CANADA","RED","MARRIED","OBJECT","STUDIES","MEDIA","ENGINE","PASSED","HENRY","AUSTRALIA","MACHINE","QUALITY","FOUNDED","HOLD","SAY","PARTIES","LETTER","JAPAN","EXPECTED","TREATMENT","NORMAL","SIGNAL","BLOOD","FINANCIAL","STATUS","VIDEO","OLDER","CARRIED","COMPARED","KNOW","WANTED","ACCEPTED","VIA","READ","EACHOTHER","TYPESOF","ANIMALS","TURNED","UNIT","FEATURE","SOUTHERN","INCREASING","MET","PREVENT","SONGS","APPLICATIONS","REQUIRE","OPENED","MARRIAGE","CONTAIN","EQUIPMENT","PLAYING","SECTION","REMAINING","PROPERTIES","ASKED","THECASE","TEN","CHARLES","ACTIVITY","WHOM","WAYS","BUILDINGS","BASIC","PROBABLY","RUNNING","MATERIALS","STORIES","EDITION","LOCATION","NOTED","CELL","ANALYSIS","RUSSIA","ROME","REMOVED","BECOMES","PAPER","ACTIVITIES","BILLION","FALL","CHILD","CUT","OPERATING","DEGREE","SHIP","OCCURS","LESSTHAN","NOVEL","COMPLETELY","EXCEPT","INSIDE","ROBERT","TROOPS","JEWISH","REPORT","CALL","FLOW","METAL","APPOINTED","OFFERED","TOLD","FREQUENCY","INITIAL","CAMPAIGN","DISCOVERED","DEFINITION","HISTORICAL","MODELS","ALLOWING","OPERATION","POLICE","POOR","WEIGHT","NOTHAVE","ANCIENT","HERE","PRIMARILY","AGREED","HIT","WEST","HEAT","SECURITY","DAVID","CLAIMED","POSITIVE","EASILY","ENVIRONMENT","SCIENTIFIC","GOING","REGIONS","ISBN","BALL","TRADITION","REACH","REQUIRES","ST.","EXTENDED","CHARGE","FEMALE","FACE","SERVE","EQUAL","ITALY","LETTERS","REFUSED","IMMEDIATELY","BELIEVE","SUPPLY","EFFECTIVE","INTERNAL","VERSIONS","CULTURAL","LEAVE","TH","MAINLY","NEGATIVE","SOLDIERS","QUESTION","SPREAD","SUGGESTED","PAUL"]

# for i in 1:2:length(most_used)
#     print("\"",uppercase(most_used[i]),"\",")
# end
# function build()
    occ = zeros(Int,50,50,5)
    for w in most_used
        for line in 1:5
            sols = [findall(x->x[line]==c,col) for c in w]
            if !(0 in [length(x) for x in sols])
                for is in 1:length(sols)-1
                    for i in sols[is],j in sols[is+1]
                        occ[i,j,line] +=1
                    end
                end
            end
        end
    end
    println(occ)
# end
# build()

pr = [Int[] for i in 1:50]

for i in 1:50,j in 1:50
    if length([0 for i in occ[i,j,:] if i==0]) < 2
        push!(pr[i],j)
    end
end

global max = 0

function chain(pr,c,tl,ch)
    # println(ch)
    global max
    if length(pr[c]) == 0 || tl> 51
        if length(ch)>=max
            max = length(ch)
            printm(ch)
            println()
        end
    else
        for i in pr[c]
            if !(i in ch)
            push!(ch,i)
            chain(pr,i,tl+1,ch)
            pop!(ch)
            end
        end
    end
end

for i in eachindex(pr)
    c = i
    chain(pr,c,0,Int[])
end
